### ISSUE TITLE
Making butter from milk destroys buckets

### ISSUE THREAD

**Issue by engineer-pearl** [rubenwardy/food#28]
Most recipes involving buckets leave an empty bucket in the crafting grid. Crafting food:butter, however, removed the buckets.

**Comment by engineer-pearl** [comment]
I found something that might be used to fix it, but so far I have not been successful.
The line of code can be found on the bottom of this page: http://dev.minetest.net/minetest.register_craft

Now, I know this could cause problems with the fact that not all supported versions of milk are in buckets, however that could be fixed by having two groups, one for milk alone and one for milk in a bucket.

I will comment again when I have something that will load.

**Comment by HybridDog** [comment]
Using replacements should work. It only works if stack_max is 1.

**Comment by engineer-pearl** [comment]
It should, but with the code 

> food.module("butter", function()  
>	minetest.register_craftitem(":food:butter", {  
>		description = S("Butter"),  
>		inventory_image = "food_butter.png",  
>		groups = {food_butter=1}  
>	})  
>	food.craft({  
>		output = "food:butter",  
>		recipe = {"group:food_milkbucket","group:food_milkbucket"},  
>			replacements = { {"group:food_milkbucket", "default:dirt"} },  
>	})  
>	food.craft({  
>		output = "food:butter",  
>		recipe = {  
>			{"group:food_milk","group:food_milk"},  
>		}  
>	})  
> end, true)  

(I've also modified support so that milk is split into milk and milk bucket)

> food.support("milk", {  
>	"animalmaterials:milk",  
>	"my_mobs:milk_glass_cup",  
>	"mtfoods:dandelion_milk"  
> })  
> food.support("milkbucket", {  
>	"jkanimals:bucket_milk",  
>	"mobs:bucket_milk",  
> })  

I get an invalid crafting recipe error. Everything works but the replacement, and the problem isn't that it wants doubles. Here's the response saved in debug.txt:

`2016-07-30 21:40:34: ERROR[Main]: ModError: Invalid crafting recipe (output="food:butter")  
2016-07-30 21:40:34: ERROR[Main]: Check debug.txt for details.`

(Please forgive the lack of tabs - github did not want to include them)

**Comment by HybridDog** [comment]
l don't know food's craft function

**Comment by engineer-pearl** [comment]
Hey, I've submitted a pull request with a fix to this problem. Turns out I didn't have my syntax right when I tried it the first time.  The current code:
```
food.module("butter", function()
	minetest.register_craftitem(":food:butter", {
		description = S("Butter"),
		inventory_image = "food_butter.png",
		groups = {food_butter=1}
	})
	food.craft({
		output = "food:butter",
		recipe = {{"group:food_milkbucket","group:food_milkbucket"}},
		replacements = { 
		    {"group:food_milkbucket","bucket:bucket_empty"},
		    {"group:food_milkbucket","bucket:bucket_empty"} 
		},
	})
	food.craft({
	output = "food:butter",
	recipe = {{"group:food_milk","group:food_milkbucket"}},
	replacements = { 
	    {"group:food_milkbucket","bucket:bucket_empty"},
	},
	})
	food.craft({
		output = "food:butter",
		recipe = {
			{"group:food_milk","group:food_milk"},
		}
	})
end, true)
```

It may have been the missing braces that caused the failure. 

(Note: this version of the fix is compatible with mixing milk buckets with milk not in buckets.)

**Comment by partsfps** [comment]
using some [restaurant equipment parts](https://www.partsfps.com) then easy to making butter from milk destroys buckets.

**Comment by PartsIPS** [comment]
Yes! Really this make some sense.. So better to use some [Appliance Parts and Supplies](https://www.partsips.com/) to have this work..
